# Author: Smit Patel
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:$SHORT_SHA",
        "./backend",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:$SHORT_SHA",
        "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:latest",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "backend",
        "--image",
        "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]

images:
  - "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:$SHORT_SHA"
  - "us-central1-docker.pkg.dev/csci-5709-g10/csci-5709-g10/backend:latest"

options:
  logging: CLOUD_LOGGING_ONLY
